RobertoGol23/TrainProject

progetto/src/test/java/test/Test02.java, progetto/src/test/java/test/Test5.java
=> merge finale2

progetto/src/main/java/eccezioni/eccezioniSigla/MarcaNonValidaException.java, progetto/src/main/java/entity/classi_astratte/TrenoBuilder.java, progetto/src/main/java/entity/treno/Locomotiva.java, progetto/src/main/java/entity/treno/Treno.java, progetto/src/main/java/utility/TrenoUtility.java, progetto/src/test/java/test/Test00.java
- Aggiunta la classe TrenoUtility e creato all'interno un controllo per la sigla e la marca, in modo che lanci eccezioni nel caso in cui ci siano errori.
- Snellita la classe TrenoBuilder
- Spostato il blocco switch per la restituzione della marca dato un intero nella classe TrenoUtility
- Aggiunta un'eccezione per la marca del treno inesistente
- Aggiunto test00 per la sola creazione e stampa dei treni
- Sistemata stampa dei vagoni dei treni
=> Aggiunta TrenoUtility e modificata la classe TrenoBuilder

progetto/src/main/java/configuration/JpaConfig.java, progetto/src/main/java/entity/acquisto/Acquisto.java, progetto/src/main/java/entity/dao/AcquistoDAO.java, progetto/src/main/java/entity/dao/VotoDAO.java, progetto/src/main/java/entity/treno/Treno.java, progetto/src/main/java/entity/user/User.java, progetto/src/test/java/test/Test00.java, progetto/src/test/java/test/Test01.java, progetto/src/test/java/test/Test02.java, progetto/src/test/java/test/Test03.java, progetto/src/test/java/test/Test04.java, progetto/src/test/java/test/Test05.java, progetto/src/test/java/test/Test06.java, progetto/src/test/java/test/Test07.java, progetto/src/test/java/test/Test09.java, progetto/src/test/java/test/Test10.java, progetto/src/test/java/test/testEccezioni/TestEccezioni01.java
Creata la classe Acquisto, la classe AcquistoDAO, 
Inserito dentro user e dentro treno la lista di acquisti,
Creato test10
Inserito dentro user il wallet
=> Creata la gestione degli acquisti

progetto/src/main/java/configuration/JpaConfig.java, progetto/src/main/java/eccezioni/eccezioniGeneriche/MarcaNonValidaException.java, progetto/src/main/java/eccezioni/eccezioniGeneriche/SoldiNonSufficientiException.java, progetto/src/main/java/entity/acquisto/Acquisto.java, progetto/src/main/java/entity/treno/Treno.java, progetto/src/main/java/utility/TrenoUtility.java, progetto/src/test/java/test/Test09.java, progetto/src/test/java/test/Test10.java
Aggiunta di eccezione per soldi non sufficienti + creazione metodo getPrezzoTotaleTreno()
=> Eccezione soldi non sufficienti + getPrezzoTotaleTreno()

progetto/src/main/java/configuration/JpaConfig.java, progetto/src/main/java/entity/acquisto/Acquisto.java, progetto/src/main/java/entity/user/User.java, progetto/src/test/java/test/testAcquisti/Test10.java
Gestita la modifica del wallet di un utente dopo l'acquisto di un treno
=> Modifica del wallet dopo l'acquisto di un treno

progetto/src/main/java/configuration/JpaConfig.java, progetto/src/main/java/entity/votazioni/Voto.java, progetto/src/test/java/test/testVoti/Test08.java
Gestita la possibilita' di votare piu' volte lo stesso treno, nel caso lancia una eccezione e non salva il valore del voto, da pensare se invece si preferisce fare una update
=> Roberto's branch

progetto/src/main/java/configuration/JpaConfig.java, progetto/src/main/java/entity/dao/TrenoDAO.java, progetto/src/test/java/test/TestGenerale.java
addServizio(Long id_treno, int id_vagone, String servizio) //modificato questa riga passando l'id invece dell'oggetto treno
Treno treno = getTrenoById(id_treno); //creato un oggetto treno dato l'id, quindi preso dal db e non passato come oggetto java
il resto è rimasto invariato
=> Corretto e modificato metodo addServizio

progetto/pom.xml, progetto/src/main/webapp/index.jsp
=> settato il serveron

progetto/src/main/webapp/index.jsp
=> pagina di prova su index.jsp

progetto/pom.xml, progetto/src/main/java/entity/classi_astratte/TrenoBuilder.java, progetto/src/main/java/entity/dao/TrenoDAO.java, progetto/src/main/java/entity/treno/Treno.java, progetto/src/main/java/utility/TrenoUtility.java, progetto/src/main/webapp/WEB-INF/views/dashboard.jsp, progetto/src/test/java/test/TestGenerale.java, progetto/src/test/java/test/testTrenieServizi/Test01.java, progetto/src/test/java/test/testTrenieServizi/Test06.java, progetto/src/test/java/test/testTrenieServizi/Test07.java
---[MODIFICATO]---------------------------------------------------------------------------------------------------------------------------------------------
/**
* Metodo che consente di rimuovere uno o più vagoni dato l'id di un treno, passandogli id da rimuovere
* Dal sito web l'utente selezionerà dalle checkbox i vagoni da rimuovere. Per evitare errori si può evitare di mettere la checkbox nella locomotiv, * così non sarà possibile per l'utente rimuoverla e non sarà da gestire negli errori * @param id_treno, id del treno da cui togliere i vagoni * @param idVagoni, questa lista di id dei vagoni non rappresenta una raccolta di id dei vagoni presenti sul db. Quelli sono fissi. * Gli id che saranno passati qui, saranno quelli scelti dall'utente dalla lista vagoni, quindi a seconda della …
=> Aggiunta e rimozione multipla dei vagoni

progetto/src/main/java/configuration/JpaConfig.java, progetto/src/main/java/controller/UserController.java, progetto/src/main/java/entity/dao/UserDAO.java, progetto/src/main/webapp/WEB-INF/views/login.jsp
Modificato il file UserController e login.jsp
=> Aggiunto controllo su utente e password errati

progetto/src/main/java/controller/UserController.java, progetto/src/main/java/entity/user/User.java, progetto/src/main/webapp/WEB-INF/views/register.jsp
Impostato valore wallet alla registrazione a 0
=> Rimosso wallet nella registrazione

progetto/src/main/java/configuration/JpaConfig.java, progetto/src/main/java/controller/UserController.java, progetto/src/main/java/entity/dao/TrenoDAO.java, progetto/src/main/webapp/WEB-INF/views/editProfile.jsp, progetto/src/main/webapp/WEB-INF/views/login.jsp, progetto/src/main/webapp/WEB-INF/views/register.jsp, progetto/src/test/java/test/testTrenieServizi/Test07.java
- modificata impaginazione editProfile
- aggiunti metodi per il controllo del peso del treno e peso trasportabile
- aggiunto metodo che restituisce la somma dei vagoni dato un id del treno sul db
=> Controllo peso dopo aver aggiunto vagoni

progetto/src/main/java/controller/CreateTrainController.java, progetto/src/main/webapp/WEB-INF/dispatcher-servlet.xml, progetto/src/main/webapp/WEB-INF/views/createTrain.jsp, progetto/src/main/webapp/WEB-INF/views/dashboard.jsp, progetto/src/main/webapp/WEB-INF/views/trainSuccess.jsp
aggiunto:
-createTrenoController
-createTrain.jsp
-trainSuccess.jsp
-aggiornata dashboard
=> creato la CreateTrainController e le jps annesse

progetto/src/main/java/controller/TrainController.java, progetto/src/main/java/entity/classi_astratte/Vagone.java, progetto/src/main/webapp/WEB-INF/views/dashboard/train/addServiceComplete.jsp, progetto/src/test/java/test/testTrenieServizi/Test03.java
crea sto treno con questi magnifici servizi
=> ORA FUNZIONA

progetto/src/main/java/controller/TrainController.java, progetto/src/main/java/eccezioni/eccezioniGeneriche/ServizioGiaPresenteException.java, progetto/src/main/java/entity/dao/ServizioDAO.java, progetto/src/main/java/utility/ServiziUtility.java, progetto/src/main/webapp/WEB-INF/views/dashboard/train/createTrain.jsp, progetto/src/test/java/test/TestGenerale.java, progetto/src/test/java/test/testTrenieServizi/Test03.java, progetto/src/test/java/test/testTrenieServizi/Test05.java, progetto/src/test/java/test/testTrenieServizi/Test08.java, progetto/src/test/java/test/testUser/Test07.java
Aggiunto un sistema per registrare sul database tutti i servizi, che viene lanciato alla creazione di ogni treno. Solo se i servizi non sono presenti li aggiunge, altrimenti li ignora gestendo l'eccezione.
La classe ServiziUtility dispone di due metodi,
creaListaServizi() che restituisce una lista con tutti i servizi
e
aggiungiServiziAlDB() che prende in input un oggetto ServizioDAO e aggiunge al database solamente i servizi che non sono presenti, gestendo l'eccezione di Hibernate org.hibernate.exception.ConstraintViolationException
=> Aggiunta classe ServiziUtility e gestione inserimento servizi automatico

progetto/src/main/java/controller/TrainController.java, progetto/src/main/webapp/WEB-INF/views/dashboard/home.jsp, progetto/src/main/webapp/WEB-INF/views/dashboard/train/creaTrenoProva.jsp
- aggiunta una nuova pagina con un'interfaccia diversa per inserire la sigla all'interno di creaTreno
- aggiunto il pulsante apposito dentro la dashboard/home
- aggiunta gestione della pagina dentro la classe TrainController
=> Aggiunto creaTrenoProva

progetto/src/main/java/configuration/JpaConfig.java, progetto/src/main/java/controller/GenericController.java, progetto/src/main/java/entity/dao/TrenoDAO.java, progetto/src/main/java/entity/dao/UserDAO.java
Modifica pagina di login con controllo su utente e poi su password Aggiunto metodo
/**
* Metodo che verifica se la password è corretta per un dato indirizzo email
* @param email l'email dell'utente
* @param password, la password da verificare
* @return true, se la password è corretta, false altrimenti
*/
public boolean checkPasswordByUser(String email, String password) {
CriteriaBuilder criteriaBuilder = em.getCriteriaBuilder();
CriteriaQuery<User> criteriaQuery = criteriaBuilder.createQuery(User.class);
Root<User> userRoot = criteriaQuery.from(User.class);
// Crea il predicate per filtrare l'utente tramite l'email
Predicate emailPredicate = criteriaBuilder.equal(userRoot.get("email"), email);
criteriaQuery.select(userRoot).where(emailPredicate);
// Esegui la query e metti il risultato in …
=> Bux fix pagina di login + controlli aggiunti

progetto/src/main/java/controller/TrainController.java, progetto/src/main/java/utility/TrenoUtility.java, progetto/src/main/webapp/WEB-INF/views/dashboard/home.jsp, progetto/src/main/webapp/WEB-INF/views/dashboard/train/addServiceComplete.jsp, progetto/src/main/webapp/WEB-INF/views/dashboard/train/addWagons.jsp, progetto/src/main/webapp/WEB-INF/views/dashboard/train/creaTrenoDinamico.jsp, progetto/src/main/webapp/WEB-INF/views/dashboard/train/createTrain.jsp, progetto/src/main/webapp/WEB-INF/views/dashboard/train/modifyWagonServices.jsp, progetto/src/main/webapp/WEB-INF/views/dashboard/train/modifyWagons.jsp, progetto/src/main/webapp/WEB-INF/views/dashboard/train/removeWagons.jsp, progetto/src/main/webapp/WEB-INF/views/dashboard/train/trainModifyFail.jsp, progetto/src/main/webapp/WEB-INF/views/dashboard/train/trainModifySuccess.jsp, progetto/src/main/webapp/WEB-INF/views/dashboard/train/trainSuccess.jsp, progetto/src/main/webapp/WEB-INF/views/dashboard/train/viewTrain.jsp, progetto/src/main/webapp/WEB-INF/views/dashboard/user/accountDeleted.jsp, progetto/src/main/webapp/WEB-INF/views/dashboard/user/editProfile.jsp, progetto/src/main/webapp/WEB-INF/views/dashboard/user/ricarica.jsp, progetto/src/main/webapp/WEB-INF/views/dashboard/user/ricaricaConfirmed.jsp, progetto/src/main/webapp/WEB-INF/views/dashboard/user/viewPurchasedTrains.jsp, progetto/src/main/webapp/WEB-INF/views/dashboard/user/viewTrains.jsp, progetto/src/main/webapp/WEB-INF/views/dashboard/user/wallet.jsp, progetto/src/main/webapp/WEB-INF/views/market/trainDetails.jsp, progetto/src/main/webapp/WEB-INF/views/navbar.jsp
- aggiunta la modifica dei servizi per ogni vagone
- rimossa la possibilità di aggiungere un servizio ad una locomotiva
- aggiunto il controllo per evitare di inserire lo stesso servizio due volte grazie al metodo isServicePresent() dentro TrenoUtility
=> Correzione bug contentType + modifica servizi vagone

progetto/src/main/java/configuration/JpaConfig.java, progetto/src/main/webapp/WEB-INF/views/dashboard/home.jsp, progetto/src/main/webapp/WEB-INF/views/dashboard/train/addServiceComplete.jsp, progetto/src/main/webapp/WEB-INF/views/dashboard/train/addServiceFailed.jsp, progetto/src/main/webapp/WEB-INF/views/dashboard/train/addWagons.jsp, progetto/src/main/webapp/WEB-INF/views/dashboard/train/cloneSuccess.jsp, progetto/src/main/webapp/WEB-INF/views/dashboard/train/cloneTrain.jsp, progetto/src/main/webapp/WEB-INF/views/dashboard/train/modifyWagonServices.jsp, progetto/src/main/webapp/WEB-INF/views/dashboard/train/trainModifyFail.jsp, progetto/src/main/webapp/WEB-INF/views/dashboard/train/trainModifySuccess.jsp, progetto/src/main/webapp/css/basicStyle.css
Primo grande update della grafica delle pagine. Aggiornate le seguenti in blu:
=> Merge Update grafica pagine 1

progetto/src/main/java/controller/TrainController.java, progetto/src/main/webapp/WEB-INF/views/dashboard/admin/manageUsers.jsp, progetto/src/main/webapp/WEB-INF/views/dashboard/admin/showPurchases.jsp, progetto/src/main/webapp/WEB-INF/views/dashboard/home.jsp, progetto/src/main/webapp/WEB-INF/views/dashboard/train/addWagons.jsp, progetto/src/main/webapp/WEB-INF/views/dashboard/train/creaTrenoDinamico.jsp, progetto/src/main/webapp/WEB-INF/views/dashboard/train/createTrain.jsp, progetto/src/main/webapp/WEB-INF/views/dashboard/train/viewTrain.jsp, progetto/src/main/webapp/css/trainAnimatioStyle.css
- sistemata la creazione del treno dinamico, aggiunto i controlli e scelta del nome e marca
- aggiunta grafica nelle opzioni da amministratore
- aggiunta rilevazione eccezioni generiche in createTrain
=> Sistemato crea treno dinamico, aggiunta grafica

progetto/src/main/java/controller/TrainController.java, progetto/src/main/webapp/WEB-INF/views/dashboard/train/removeWagons.jsp
Aggiunto un controllo nel caso in cui un utente provi a rimuovere un vagone senza averne selezionato nessuno
=> Aggiunto controllo rimuovi vagoni

progetto/src/main/webapp/WEB-INF/views/dashboard/train/viewTrain.jsp, progetto/src/main/webapp/WEB-INF/views/market/purchaseTrain.jsp, progetto/src/main/webapp/WEB-INF/views/market/trainDetails.jsp
Aggiunte immagini corrette e ridimensionate durante i dettagli prima dell'acquisto
=> Aggiunto margine fondo pagina e aggiunte immagini
